### ISSUE TITLE
can't compile nuvolaruntime on Fedora 25

### ISSUE THREAD

**Issue by martinkg** [tiliado/nuvolaruntime#349]
```
$ rpmbuild -ba nuvolaruntime.spec 
Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.JkPRxb
+ umask 022
+ cd /home/martin/rpmbuild/BUILD
+ cd /home/martin/rpmbuild/BUILD
+ rm -rf nuvolaruntime-4.4.0
+ /usr/bin/gzip -dc /home/martin/rpmbuild/SOURCES/nuvolaruntime-4.4.0.tar.gz
+ /usr/bin/tar -xof -
+ STATUS=0
+ '[' 0 -ne 0 ']'
+ cd nuvolaruntime-4.4.0
+ /usr/bin/chmod -Rf a+rX,u+w,g-w,o-w .
+ rm ./waf
+ rm -rf ./.waf
+ rm branding/default.json
+ exit 0
Executing(%build): /bin/sh -e /var/tmp/rpm-tmp.dQ5IhL
+ umask 022
+ cd /home/martin/rpmbuild/BUILD
+ cd nuvolaruntime-4.4.0
+ waf-3 configure --prefix=/usr --libdir=/usr/lib64 --nounity
Setting top to                           : /home/martin/rpmbuild/BUILD/nuvolaruntime-4.4.0 
Setting out to                           : /home/martin/rpmbuild/BUILD/nuvolaruntime-4.4.0/build 
fatal: Not a git repository (or any of the parent directories): .git
Traceback (most recent call last):
  File "/usr/share/waf3/waflib/Scripting.py", line 121, in waf_entry_point
    run_commands()
  File "/usr/share/waf3/waflib/Scripting.py", line 182, in run_commands
    ctx=run_command(cmd_name)
  File "/usr/share/waf3/waflib/Scripting.py", line 173, in run_command
    ctx.execute()
  File "/usr/share/waf3/waflib/Configure.py", line 84, in execute
    super(ConfigurationContext,self).execute()
  File "/usr/share/waf3/waflib/Context.py", line 87, in execute
    self.recurse([os.path.dirname(g_module.root_path)])
  File "/usr/share/waf3/waflib/Context.py", line 128, in recurse
    user_function(self)
  File "/home/martin/rpmbuild/BUILD/nuvolaruntime-4.4.0/wscript", line 187, in configure
    add_version_info(ctx)
  File "/home/martin/rpmbuild/BUILD/nuvolaruntime-4.4.0/wscript", line 77, in add_version_info
    bare_version, n_commits, revision_id = get_git_version()
ValueError: not enough values to unpack (expected 3, got 1)
```
same behaviour as in diorite

**Comment by martinkg** [comment]
ok, was solved  https://github.com/tiliado/nuvolaruntime/commit/3af85f7d473f6a33ddab2fc7b3d6e689e0c21947
